### ISSUE TITLE
User Story overview

### ISSUE THREAD

**Issue by Diren-T** [Diren-T/capstone-project-1#1]
## Value Proposition

**As a user I would like to have an app to track the co2 emissions of my flights.** 
​

## Description

![image](https://user-images.githubusercontent.com/117982616/213446483-2cdaf3e4-237f-49a3-952b-5cc356025784.png)
​

## Acceptance Criteria

- [ ] the app displays the navigation the logo and the button to track
      ​

## Tasks

- [ ] create header with logo
- [ ] fetch API
- [ ] create navigation
- [ ] create card componente
      ​

## Complexity

L

**Comment by doemser** [comment]
This user-story should be improved in some places. 
Currently your Acceptance Criteria foresees e.g. to implement elements that do not have a function yet. This violates the principle of "only working code".

Also, this user-story sees virtually the whole app.
Try to think about which first step is necessary to have a first iteration of a working app.

I don't know where you want to go and how the API works, but I could imagine something like this:

As a user, 
I want to be able to enter my flights and look them up, 
so that I can get an overview.

AC:
- There is a form to enter your flights
- There is a list of flights

And then think about what tasks you need to do for that.

Don't try to implement styling yet, it won't bring you any functional value at this point. In the next story, you could already include the API in the form submit to determine the footprint.

**Comment by doemser** [comment]
Still I have some comments:

When I read your user-story I actually expect a list of airports without being able to do anything.
But your description then shows a form ( without submit button! ) with which I could submit flights.
But then the AC says again that there is a list of airports and there are toggles to confirm the selection. 
This does not fit together.

Please try to be as precise as possible, also your Acceptance Criteria should be much more specific:

This is the specificity you should aim for:
- The airports list displays the name, code, location, and contact information of the airport
- The user can sort the search results by various criteria such as name, location, and size
- The user can filter the search results by criteria such as location, services, and facilities

A toggle to select for the user makes no sense right now, due to it would not have a function yet.

**Comment by ThomasF85** [comment]
Hi Diren,

your user story should have a value proposition with the correct form (As a User I want to ... so that ...). Also the value proposition should be short.
Your acceptance criteria are not describing the functionality you add, for example you write:
- in the first input field you enter your departure airport
This describes how the user uses your form, not which new feature / field you add. You could write instead:
- there is an input field for the departure airport

Also please describe how the input fields behave. Are these just "ordinary" text inputs, or are these dropdowns with a list of airports? Is there autocompletion? Can the user input every possible string, or just a list of valid airport names / codes?

**Comment by Diren-T** [comment]
I hope i have taken the remark correctly

**Comment by SaschaRadojkovic** [comment]
hi Diren,  in your tasks you are always mentioning the first input field but there are 3 different input fields. and i think when i would code this there would be missing the labels connected to the input fields. 
and maybe the input fields should have a specified type and a min and max length of characters

(and i dont really know if that is a good idea or maybe to much for the first user story but maybe you could save the input as an variable and display it below the form.)

**Comment by Diren-T** [comment]
thanks for your comment @SaschaRadojkovic , is it better this way?

**Comment by SaschaRadojkovic** [comment]
[look here how he did this with input fields](https://github.com/marcterre/capstone-project/issues/3)         i think it is a good example

**Comment by Diren-T** [comment]
@SaschaRadojkovic @ThomasF85 
please look again. is not so my day today...
